// Sample data for the admin panel

// Admin users
export const adminUsers = [
  {
    id: "user-001",
    name: "Admin User",
    email: "admin@example.com",
    password: "password", // In a real app, this would be hashed
    role: "admin",
  },
  {
    id: "user-002",
    name: "Editor User",
    email: "editor@example.com",
    password: "password", // In a real app, this would be hashed
    role: "editor",
  },
]

// Orders data
export const orders = [
  {
    id: "ord-001",
    orderNumber: "ORD-12345",
    date: "2023-04-01",
    customer: {
      name: "John Doe",
      email: "john.doe@example.com",
      phone: "+1 (555) 123-4567",
    },
    items: [
      {
        name: "100W Solar Panel",
        price: 129.99,
        quantity: 2,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Inverter 1000W",
        price: 249.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 509.97,
    shipping: 0,
    discount: 0,
    total: 509.97,
    status: "delivered",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Visa",
      lastFour: "4242",
    },
    shippingAddress: {
      name: "John Doe",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
    },
    billingAddress: {
      name: "John Doe",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-01",
        time: "10:30 AM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-01",
        time: "10:35 AM",
      },
      {
        status: "Processing",
        date: "2023-04-02",
        time: "09:15 AM",
      },
      {
        status: "Shipped",
        date: "2023-04-03",
        time: "02:45 PM",
      },
      {
        status: "Delivered",
        date: "2023-04-05",
        time: "11:20 AM",
      },
    ],
  },
  {
    id: "ord-002",
    orderNumber: "ORD-12346",
    date: "2023-04-02",
    customer: {
      name: "Jane Smith",
      email: "jane.smith@example.com",
      phone: "+1 (555) 987-6543",
    },
    items: [
      {
        name: "12V DC Ceiling Fan",
        price: 89.99,
        quantity: 3,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 269.97,
    shipping: 10,
    discount: 0,
    total: 279.97,
    status: "shipped",
    paymentMethod: "PayPal",
    paymentDetails: {
      email: "jane.smith@example.com",
    },
    shippingAddress: {
      name: "Jane Smith",
      street: "456 Oak Ave",
      city: "Somewhere",
      state: "NY",
      zip: "67890",
    },
    billingAddress: {
      name: "Jane Smith",
      street: "456 Oak Ave",
      city: "Somewhere",
      state: "NY",
      zip: "67890",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-02",
        time: "03:45 PM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-02",
        time: "03:50 PM",
      },
      {
        status: "Processing",
        date: "2023-04-03",
        time: "10:30 AM",
      },
      {
        status: "Shipped",
        date: "2023-04-04",
        time: "01:15 PM",
      },
    ],
  },
  {
    id: "ord-003",
    orderNumber: "ORD-12347",
    date: "2023-04-03",
    customer: {
      name: "Robert Johnson",
      email: "robert.johnson@example.com",
      phone: "+1 (555) 456-7890",
    },
    items: [
      {
        name: "100Ah Deep Cycle Battery",
        price: 199.99,
        quantity: 2,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Inverter 1000W",
        price: 249.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 649.97,
    shipping: 0,
    discount: 50,
    total: 599.97,
    status: "processing",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Mastercard",
      lastFour: "5678",
    },
    shippingAddress: {
      name: "Robert Johnson",
      street: "789 Pine St",
      city: "Elsewhere",
      state: "TX",
      zip: "54321",
    },
    billingAddress: {
      name: "Robert Johnson",
      street: "789 Pine St",
      city: "Elsewhere",
      state: "TX",
      zip: "54321",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-03",
        time: "11:20 AM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-03",
        time: "11:25 AM",
      },
      {
        status: "Processing",
        date: "2023-04-04",
        time: "09:45 AM",
      },
    ],
  },
  {
    id: "ord-004",
    orderNumber: "ORD-12348",
    date: "2023-04-04",
    customer: {
      name: "Emily Davis",
      email: "emily.davis@example.com",
      phone: "+1 (555) 234-5678",
    },
    items: [
      {
        name: "200W Solar Panel",
        price: 229.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 229.99,
    shipping: 10,
    discount: 0,
    total: 239.99,
    status: "pending",
    paymentMethod: "Cash on Delivery",
    paymentDetails: {},
    shippingAddress: {
      name: "Emily Davis",
      street: "321 Elm St",
      city: "Nowhere",
      state: "FL",
      zip: "13579",
    },
    billingAddress: {
      name: "Emily Davis",
      street: "321 Elm St",
      city: "Nowhere",
      state: "FL",
      zip: "13579",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-04",
        time: "05:30 PM",
      },
    ],
  },
  {
    id: "ord-005",
    orderNumber: "ORD-12349",
    date: "2023-04-05",
    customer: {
      name: "Michael Wilson",
      email: "michael.wilson@example.com",
      phone: "+1 (555) 876-5432",
    },
    items: [
      {
        name: "Portable Solar Generator",
        price: 349.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "10W Solar DC Fan",
        price: 39.99,
        quantity: 2,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 429.97,
    shipping: 0,
    discount: 0,
    total: 429.97,
    status: "cancelled",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Visa",
      lastFour: "1111",
    },
    shippingAddress: {
      name: "Michael Wilson",
      street: "654 Maple Ave",
      city: "Othertown",
      state: "CA",
      zip: "24680",
    },
    billingAddress: {
      name: "Michael Wilson",
      street: "654 Maple Ave",
      city: "Othertown",
      state: "CA",
      zip: "24680",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-05",
        time: "09:15 AM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-05",
        time: "09:20 AM",
      },
      {
        status: "Cancelled",
        date: "2023-04-05",
        time: "02:30 PM",
      },
    ],
  },
  {
    id: "ord-006",
    orderNumber: "ORD-12350",
    date: "2023-04-06",
    customer: {
      name: "Sarah Thompson",
      email: "sarah.thompson@example.com",
      phone: "+1 (555) 321-6547",
    },
    items: [
      {
        name: "Solar Charge Controller",
        price: 79.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Panel Mounting Kit",
        price: 49.99,
        quantity: 2,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 179.97,
    shipping: 15,
    discount: 10,
    total: 184.97,
    status: "delivered",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Amex",
      lastFour: "9876",
    },
    shippingAddress: {
      name: "Sarah Thompson",
      street: "789 Cedar Rd",
      city: "Hillside",
      state: "NJ",
      zip: "07642",
    },
    billingAddress: {
      name: "Sarah Thompson",
      street: "789 Cedar Rd",
      city: "Hillside",
      state: "NJ",
      zip: "07642",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-06",
        time: "02:15 PM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-06",
        time: "02:20 PM",
      },
      {
        status: "Processing",
        date: "2023-04-07",
        time: "10:00 AM",
      },
      {
        status: "Shipped",
        date: "2023-04-08",
        time: "03:30 PM",
      },
      {
        status: "Delivered",
        date: "2023-04-10",
        time: "01:45 PM",
      },
    ],
  },
  {
    id: "ord-007",
    orderNumber: "ORD-12351",
    date: "2023-04-07",
    customer: {
      name: "David Martinez",
      email: "david.martinez@example.com",
      phone: "+1 (555) 789-1234",
    },
    items: [
      {
        name: "300W Solar Panel Kit",
        price: 399.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 399.99,
    shipping: 0,
    discount: 25,
    total: 374.99,
    status: "shipped",
    paymentMethod: "PayPal",
    paymentDetails: {
      email: "david.martinez@example.com",
    },
    shippingAddress: {
      name: "David Martinez",
      street: "456 Birch Ln",
      city: "Riverside",
      state: "IL",
      zip: "60546",
    },
    billingAddress: {
      name: "David Martinez",
      street: "456 Birch Ln",
      city: "Riverside",
      state: "IL",
      zip: "60546",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-07",
        time: "11:30 AM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-07",
        time: "11:35 AM",
      },
      {
        status: "Processing",
        date: "2023-04-08",
        time: "09:45 AM",
      },
      {
        status: "Shipped",
        date: "2023-04-09",
        time: "02:15 PM",
      },
    ],
  },
  {
    id: "ord-008",
    orderNumber: "ORD-12352",
    date: "2023-04-08",
    customer: {
      name: "Lisa Anderson",
      email: "lisa.anderson@example.com",
      phone: "+1 (555) 456-1234",
    },
    items: [
      {
        name: "Solar Water Pump",
        price: 129.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Panel 50W",
        price: 89.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 219.98,
    shipping: 10,
    discount: 0,
    total: 229.98,
    status: "processing",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Visa",
      lastFour: "2222",
    },
    shippingAddress: {
      name: "Lisa Anderson",
      street: "123 Willow Dr",
      city: "Springfield",
      state: "MA",
      zip: "01103",
    },
    billingAddress: {
      name: "Lisa Anderson",
      street: "123 Willow Dr",
      city: "Springfield",
      state: "MA",
      zip: "01103",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-08",
        time: "04:20 PM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-08",
        time: "04:25 PM",
      },
      {
        status: "Processing",
        date: "2023-04-09",
        time: "10:30 AM",
      },
    ],
  },
  {
    id: "ord-009",
    orderNumber: "ORD-12353",
    date: "2023-04-09",
    customer: {
      name: "James Taylor",
      email: "james.taylor@example.com",
      phone: "+1 (555) 654-3210",
    },
    items: [
      {
        name: "Solar LED Street Light",
        price: 149.99,
        quantity: 4,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 599.96,
    shipping: 0,
    discount: 50,
    total: 549.96,
    status: "pending",
    paymentMethod: "Cash on Delivery",
    paymentDetails: {},
    shippingAddress: {
      name: "James Taylor",
      street: "789 Oak St",
      city: "Greenville",
      state: "SC",
      zip: "29601",
    },
    billingAddress: {
      name: "James Taylor",
      street: "789 Oak St",
      city: "Greenville",
      state: "SC",
      zip: "29601",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-09",
        time: "09:45 AM",
      },
    ],
  },
  {
    id: "ord-010",
    orderNumber: "ORD-12354",
    date: "2023-04-10",
    customer: {
      name: "Patricia White",
      email: "patricia.white@example.com",
      phone: "+1 (555) 321-9876",
    },
    items: [
      {
        name: "Solar Battery Charger",
        price: 59.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Panel Connectors",
        price: 19.99,
        quantity: 3,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 119.96,
    shipping: 8,
    discount: 0,
    total: 127.96,
    status: "cancelled",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Mastercard",
      lastFour: "3333",
    },
    shippingAddress: {
      name: "Patricia White",
      street: "456 Pine Ave",
      city: "Lakeside",
      state: "MI",
      zip: "49221",
    },
    billingAddress: {
      name: "Patricia White",
      street: "456 Pine Ave",
      city: "Lakeside",
      state: "MI",
      zip: "49221",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-10",
        time: "01:30 PM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-10",
        time: "01:35 PM",
      },
      {
        status: "Cancelled",
        date: "2023-04-10",
        time: "04:45 PM",
      },
    ],
  },
  {
    id: "ord-011",
    orderNumber: "ORD-12355",
    date: "2023-04-11",
    customer: {
      name: "Robert Clark",
      email: "robert.clark@example.com",
      phone: "+1 (555) 789-4561",
    },
    items: [
      {
        name: "Solar Panel Cleaning Kit",
        price: 29.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Panel Tilt Mount",
        price: 89.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 119.98,
    shipping: 12,
    discount: 0,
    total: 131.98,
    status: "delivered",
    paymentMethod: "PayPal",
    paymentDetails: {
      email: "robert.clark@example.com",
    },
    shippingAddress: {
      name: "Robert Clark",
      street: "123 Maple Dr",
      city: "Hilltop",
      state: "OH",
      zip: "43026",
    },
    billingAddress: {
      name: "Robert Clark",
      street: "123 Maple Dr",
      city: "Hilltop",
      state: "OH",
      zip: "43026",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-11",
        time: "10:15 AM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-11",
        time: "10:20 AM",
      },
      {
        status: "Processing",
        date: "2023-04-12",
        time: "09:30 AM",
      },
      {
        status: "Shipped",
        date: "2023-04-13",
        time: "03:15 PM",
      },
      {
        status: "Delivered",
        date: "2023-04-15",
        time: "11:45 AM",
      },
    ],
  },
  {
    id: "ord-012",
    orderNumber: "ORD-12356",
    date: "2023-04-12",
    customer: {
      name: "Jennifer Hall",
      email: "jennifer.hall@example.com",
      phone: "+1 (555) 456-7891",
    },
    items: [
      {
        name: "Solar Inverter 2000W",
        price: 349.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 349.99,
    shipping: 0,
    discount: 0,
    total: 349.99,
    status: "shipped",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Visa",
      lastFour: "4444",
    },
    shippingAddress: {
      name: "Jennifer Hall",
      street: "456 Elm St",
      city: "Brookside",
      state: "PA",
      zip: "19008",
    },
    billingAddress: {
      name: "Jennifer Hall",
      street: "456 Elm St",
      city: "Brookside",
      state: "PA",
      zip: "19008",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-12",
        time: "03:45 PM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-12",
        time: "03:50 PM",
      },
      {
        status: "Processing",
        date: "2023-04-13",
        time: "10:15 AM",
      },
      {
        status: "Shipped",
        date: "2023-04-14",
        time: "02:30 PM",
      },
    ],
  },
  {
    id: "ord-013",
    orderNumber: "ORD-12357",
    date: "2023-04-13",
    customer: {
      name: "Michael Young",
      email: "michael.young@example.com",
      phone: "+1 (555) 123-7894",
    },
    items: [
      {
        name: "Solar Panel Extension Cables",
        price: 24.99,
        quantity: 2,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Panel Junction Box",
        price: 19.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 69.97,
    shipping: 8,
    discount: 0,
    total: 77.97,
    status: "processing",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Discover",
      lastFour: "5555",
    },
    shippingAddress: {
      name: "Michael Young",
      street: "789 Cedar Ave",
      city: "Pineville",
      state: "NC",
      zip: "28134",
    },
    billingAddress: {
      name: "Michael Young",
      street: "789 Cedar Ave",
      city: "Pineville",
      state: "NC",
      zip: "28134",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-13",
        time: "11:30 AM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-13",
        time: "11:35 AM",
      },
      {
        status: "Processing",
        date: "2023-04-14",
        time: "09:45 AM",
      },
    ],
  },
  {
    id: "ord-014",
    orderNumber: "ORD-12358",
    date: "2023-04-14",
    customer: {
      name: "Susan King",
      email: "susan.king@example.com",
      phone: "+1 (555) 789-1235",
    },
    items: [
      {
        name: "Solar Panel Monitoring System",
        price: 199.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 199.99,
    shipping: 0,
    discount: 20,
    total: 179.99,
    status: "pending",
    paymentMethod: "Cash on Delivery",
    paymentDetails: {},
    shippingAddress: {
      name: "Susan King",
      street: "123 Oak Ln",
      city: "Riverdale",
      state: "GA",
      zip: "30274",
    },
    billingAddress: {
      name: "Susan King",
      street: "123 Oak Ln",
      city: "Riverdale",
      state: "GA",
      zip: "30274",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-14",
        time: "02:45 PM",
      },
    ],
  },
  {
    id: "ord-015",
    orderNumber: "ORD-12359",
    date: "2023-04-15",
    customer: {
      name: "William Scott",
      email: "william.scott@example.com",
      phone: "+1 (555) 456-1235",
    },
    items: [
      {
        name: "Solar Panel Mounting Rails",
        price: 89.99,
        quantity: 1,
        image: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Solar Panel Clamps",
        price: 24.99,
        quantity: 4,
        image: "/placeholder.svg?height=40&width=40",
      },
    ],
    subtotal: 189.95,
    shipping: 15,
    discount: 0,
    total: 204.95,
    status: "cancelled",
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardType: "Visa",
      lastFour: "6666",
    },
    shippingAddress: {
      name: "William Scott",
      street: "456 Pine St",
      city: "Mountainview",
      state: "CO",
      zip: "80439",
    },
    billingAddress: {
      name: "William Scott",
      street: "456 Pine St",
      city: "Mountainview",
      state: "CO",
      zip: "80439",
    },
    timeline: [
      {
        status: "Order Placed",
        date: "2023-04-15",
        time: "09:30 AM",
      },
      {
        status: "Payment Confirmed",
        date: "2023-04-15",
        time: "09:35 AM",
      },
      {
        status: "Cancelled",
        date: "2023-04-15",
        time: "01:45 PM",
      },
    ],
  },
]
// Customer messages data
export const messages = [
  {
    id: "msg-001",
    name: "David Brown",
    email: "david.brown@example.com",
    phone: "+1 (555) 111-2222",
    message:
      "I'm interested in installing solar panels for my home. Could you provide more information about your residential installation services and what would be the best option for a 2000 sq ft house?",
    date: "2023-04-01",
    status: "replied",
    reply: {
      text: "Hi David,\n\nThank you for your interest in our solar panel installation services. For a 2000 sq ft house, we typically recommend our 5kW system which includes 15-20 panels depending on your energy consumption.\n\nI'd be happy to schedule a free consultation to assess your specific needs and provide a detailed quote. Please let me know when would be a convenient time for you.\n\nBest regards,\nSolar Shine Electro Team",
      date: "2023-04-02",
    },
  },
  {
    id: "msg-002",
    name: "Sarah Miller",
    email: "sarah.miller@example.com",
    phone: "+1 (555) 333-4444",
    message:
      "I recently purchased a 100W Solar Panel from your store but it arrived with a small crack in the corner. I'd like to request a replacement under warranty.",
    date: "2023-04-02",
    status: "new",
  },
  {
    id: "msg-003",
    name: "James Wilson",
    email: "james.wilson@example.com",
    phone: "+1 (555) 555-6666",
    message:
      "Do you offer installation services for the DC ceiling fans? I've purchased three units and need professional installation.",
    date: "2023-04-03",
    status: "read",
  },
  {
    id: "msg-004",
    name: "Lisa Johnson",
    email: "lisa.johnson@example.com",
    phone: "+1 (555) 777-8888",
    message:
      "I'm looking for a complete off-grid solar solution for my cabin. It's about 800 sq ft with basic appliances. Could you recommend a package?",
    date: "2023-04-04",
    status: "new",
  },
  {
    id: "msg-005",
    name: "Robert Davis",
    email: "robert.davis@example.com",
    phone: "+1 (555) 999-0000",
    message:
      "I'm having trouble with my solar inverter that I purchased last month. It keeps shutting down during peak sunlight hours. Can someone from your technical team contact me?",
    date: "2023-04-05",
    status: "read",
  },
  {
    id: "msg-006",
    name: "Jennifer Martinez",
    email: "jennifer.martinez@example.com",
    phone: "+1 (555) 123-4567",
    message:
      "I'd like to know if your solar panels come with a bird protection system. I've heard birds can damage the panels by nesting under them.",
    date: "2023-04-06",
    status: "replied",
    reply: {
      text: "Hello Jennifer,\n\nThank you for your inquiry. Yes, we offer bird protection systems that can be installed with our solar panels. These systems prevent birds from nesting under the panels while maintaining proper ventilation.\n\nThe bird guard kit costs $149.99 and can be added to any solar panel installation. Would you like me to include this in your quote?\n\nBest regards,\nSolar Shine Electro Team",
      date: "2023-04-07",
    },
  },
  {
    id: "msg-007",
    name: "Thomas Anderson",
    email: "thomas.anderson@example.com",
    phone: "+1 (555) 987-6543",
    message:
      "I'm interested in your solar water heater system. Can you provide specifications and installation requirements?",
    date: "2023-04-07",
    status: "new",
  },
  {
    id: "msg-008",
    name: "Patricia Thompson",
    email: "patricia.thompson@example.com",
    phone: "+1 (555) 456-7890",
    message: "How often should solar panels be cleaned for optimal performance? Do you offer maintenance services?",
    date: "2023-04-08",
    status: "read",
  },
  {
    id: "msg-009",
    name: "Daniel White",
    email: "daniel.white@example.com",
    phone: "+1 (555) 234-5678",
    message:
      "I need a quote for a commercial solar installation for my warehouse (approx. 10,000 sq ft). Please contact me to discuss options.",
    date: "2023-04-09",
    status: "new",
  },
  {
    id: "msg-010",
    name: "Nancy Harris",
    email: "nancy.harris@example.com",
    phone: "+1 (555) 876-5432",
    message:
      "The solar charge controller I purchased last week isn't working properly. The display shows error code E03. What should I do?",
    date: "2023-04-10",
    status: "read",
  },
  {
    id: "msg-011",
    name: "Christopher Martin",
    email: "christopher.martin@example.com",
    phone: "+1 (555) 321-6547",
    message:
      "Do you offer financing options for your solar panel systems? I'm interested in the 5kW system but need payment plans.",
    date: "2023-04-11",
    status: "replied",
    reply: {
      text: "Hi Christopher,\n\nYes, we offer several financing options through our partners:\n1. 12-month interest-free plan\n2. 3-year loan at 4.9% APR\n3. 5-year loan at 5.9% APR\n\nI can send you detailed information about each option. Please let me know which one you'd like to explore further.\n\nBest regards,\nSolar Shine Electro Team",
      date: "2023-04-12",
    },
  },
  {
    id: "msg-012",
    name: "Karen Clark",
    email: "karen.clark@example.com",
    phone: "+1 (555) 789-1234",
    message: "I'm considering solar for my RV. What portable solar solutions do you recommend for full-time RV living?",
    date: "2023-04-12",
    status: "new",
  },
  {
    id: "msg-013",
    name: "Matthew Lewis",
    email: "matthew.lewis@example.com",
    phone: "+1 (555) 456-1234",
    message:
      "How long does the installation process typically take for a residential solar system? I need to plan accordingly.",
    date: "2023-04-13",
    status: "read",
  },
  {
    id: "msg-014",
    name: "Lisa Walker",
    email: "lisa.walker@example.com",
    phone: "+1 (555) 654-3210",
    message:
      "Can you explain the difference between monocrystalline and polycrystalline solar panels? Which would be better for my home in a cloudy climate?",
    date: "2023-04-14",
    status: "new",
  },
  {
    id: "msg-015",
    name: "George Allen",
    email: "george.allen@example.com",
    phone: "+1 (555) 321-9876",
    message:
      "I received my solar panel mounting kit but it's missing some bolts. How can I get the missing parts quickly?",
    date: "2023-04-15",
    status: "read",
  },
]

// Newsletter subscribers data
export const newsletters = [
  {
    id: "news-001",
    email: "john.smith@example.com",
    date: "2023-03-15",
    source: "Footer Form",
  },
  {
    id: "news-002",
    email: "mary.johnson@example.com",
    date: "2023-03-18",
    source: "Popup Form",
  },
  {
    id: "news-003",
    email: "robert.williams@example.com",
    date: "2023-03-20",
    source: "Footer Form",
  },
  {
    id: "news-004",
    email: "jennifer.brown@example.com",
    date: "2023-03-22",
    source: "Checkout Page",
  },
  {
    id: "news-005",
    email: "michael.davis@example.com",
    date: "2023-03-25",
    source: "Footer Form",
  },
  {
    id: "news-006",
    email: "elizabeth.miller@example.com",
    date: "2023-03-28",
    source: "Popup Form",
  },
  {
    id: "news-007",
    email: "david.wilson@example.com",
    date: "2023-03-30",
    source: "Checkout Page",
  },
  {
    id: "news-008",
    email: "sarah.moore@example.com",
    date: "2023-04-01",
    source: "Footer Form",
  },
  {
    id: "news-009",
    email: "james.taylor@example.com",
    date: "2023-04-03",
    source: "Popup Form",
  },
  {
    id: "news-010",
    email: "patricia.anderson@example.com",
    date: "2023-04-05",
    source: "Footer Form",
  },
  {
    id: "news-011",
    email: "thomas.jackson@example.com",
    date: "2023-04-07",
    source: "Checkout Page",
  },
  {
    id: "news-012",
    email: "nancy.white@example.com",
    date: "2023-04-09",
    source: "Popup Form",
  },
  {
    id: "news-013",
    email: "daniel.harris@example.com",
    date: "2023-04-11",
    source: "Footer Form",
  },
  {
    id: "news-014",
    email: "lisa.martin@example.com",
    date: "2023-04-13",
    source: "Checkout Page",
  },
  {
    id: "news-015",
    email: "paul.thompson@example.com",
    date: "2023-04-15",
    source: "Popup Form",
  },
]

