// Categories data
export const categories = [
  {
    id: "cat-001",
    name: "Solar Panels",
    slug: "solar-panels",
    description: "High-efficiency solar panels for residential and commercial use",
    productCount: 4,
  },
  {
    id: "cat-002",
    name: "AC/DC Fans",
    slug: "fans",
    description: "Energy-efficient fans that run on AC or DC power",
    productCount: 3,
  },
  {
    id: "cat-003",
    name: "Solar Inverters",
    slug: "inverters",
    description: "Convert DC power from solar panels to AC power for your home",
    productCount: 3,
  },
  {
    id: "cat-004",
    name: "Dry Batteries",
    slug: "batteries",
    description: "Reliable energy storage solutions for solar systems",
    productCount: 2,
  },
  {
    id: "cat-005",
    name: "Charge Controllers",
    slug: "controllers",
    description: "Regulate voltage and current from solar panels to batteries",
    productCount: 1,
  },
  {
    id: "cat-006",
    name: "Solar Lighting",
    slug: "lighting",
    description: "Outdoor and indoor lighting powered by solar energy",
    productCount: 2,
  },
  {
    id: "cat-007",
    name: "Portable Power Stations",
    slug: "power-stations",
    description: "Compact, all-in-one solar-powered energy storage systems",
    productCount: 1,
  },
  {
    id: "cat-008",
    name: "Cables & Connectors",
    slug: "cables-connectors",
    description: "Wiring and connectors for complete solar setup",
    productCount: 0,
  },
  {
    id: "cat-009",
    name: "Mounting Equipment",
    slug: "mounting",
    description: "Hardware for securely mounting solar panels",
    productCount: 0,
  },
  {
    id: "cat-010",
    name: "Monitoring Devices",
    slug: "monitoring",
    description: "Smart monitoring systems for solar power usage",
    productCount: 0,
  },
  {
    id: "cat-011",
    name: "Flexible Panels",
    slug: "flexible-panels",
    description: "Lightweight and bendable panels for mobile applications",
    productCount: 1,
  },
  {
    id: "cat-012",
    name: "Solar Kits",
    slug: "solar-kits",
    description: "All-in-one kits for quick and easy solar installation",
    productCount: 1,
  },
  {
    id: "cat-013",
    name: "Smart Home Integration",
    slug: "smart-home",
    description: "Devices that integrate solar with smart home systems",
    productCount: 0,
  },
  {
    id: "cat-014",
    name: "Cooling Solutions",
    slug: "cooling",
    description: "Solar-powered air cooling systems",
    productCount: 0,
  },
  {
    id: "cat-015",
    name: "Accessories",
    slug: "accessories",
    description: "Miscellaneous add-ons and tools for solar products",
    productCount: 0,
  },
]

export const products = [
  {
    id: "solar-panel-100w",
    name: "100W Solar Panel",
    description: "High-efficiency monocrystalline solar panel for residential use",
    fullDescription:
      "Our 100W solar panel is designed for optimal performance in all weather conditions. Made with high-efficiency monocrystalline cells, this panel offers excellent conversion rates and durability. Perfect for residential installations, RVs, or small off-grid systems.",
    price: 129.99,
    oldPrice: 149.99,
    category: "solar-panels",
    stock: 50,
    featured: true,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 128,
    date: "2023-05-15",
    specifications: [
      { name: "Power Output", value: "100W" },
      { name: "Cell Type", value: "Monocrystalline" },
      { name: "Dimensions", value: "47.3 x 21.3 x 1.4 inches" },
      { name: "Weight", value: "13.2 lbs" },
      { name: "Warranty", value: "25 years" },
    ],
    reviewsList: [
      {
        name: "John D.",
        rating: 5,
        date: "2023-10-12",
        comment: "Great quality panel, easy to install and performing well.",
      },
      { name: "Sarah M.", rating: 4, date: "2023-09-05", comment: "Good value for money. Works as expected." },
    ],
  },
  {
    id: "solar-inverter-1000w",
    name: "1000W Solar Inverter",
    description: "Pure sine wave inverter for solar power systems",
    fullDescription:
      "This 1000W pure sine wave inverter is designed specifically for solar power systems. It efficiently converts DC power from your solar panels or batteries into AC power for your home appliances. Features multiple protection systems and a digital display for monitoring.",
    price: 249.99,
    category: "inverters",
    stock: 35,
    featured: true,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 94,
    date: "2023-06-20",
    specifications: [
      { name: "Power Output", value: "1000W" },
      { name: "Input Voltage", value: "12V DC" },
      { name: "Output Voltage", value: "110V AC" },
      { name: "Wave Form", value: "Pure Sine Wave" },
      { name: "Efficiency", value: "90%" },
    ],
  },
  {
    id: "solar-battery-100ah",
    name: "100Ah Deep Cycle Battery",
    description: "Maintenance-free deep cycle battery for solar energy storage",
    price: 199.99,
    category: "batteries",
    stock: 20,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.3,
    reviews: 76,
    date: "2023-07-10",
  },
  {
    id: "dc-ceiling-fan",
    name: "12V DC Ceiling Fan",
    description: "Energy-efficient ceiling fan that runs directly on DC power",
    price: 89.99,
    oldPrice: 109.99,
    category: "fans",
    stock: 45,
    featured: true,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.2,
    reviews: 53,
    date: "2023-08-05",
  },
  {
    id: "solar-panel-200w",
    name: "200W Solar Panel",
    description: "High-power solar panel for larger installations",
    price: 229.99,
    category: "solar-panels",
    stock: 15,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.8,
    reviews: 42,
    date: "2023-09-12",
  },
  {
    id: "portable-solar-generator",
    name: "Portable Solar Generator",
    description: "All-in-one portable power station with built-in battery",
    price: 349.99,
    category: "inverters",
    stock: 10,
    featured: true,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 38,
    date: "2023-10-01",
  },
  {
    id: "solar-dc-fan",
    name: "10W Solar DC Fan",
    description: "Portable fan that can run directly from a small solar panel",
    price: 39.99,
    category: "fans",
    stock: 60,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.0,
    reviews: 29,
    date: "2023-11-15",
  },
  {
    id: "lithium-battery-pack",
    name: "48V Lithium Battery Pack",
    description: "High-capacity lithium battery pack for solar energy storage",
    price: 899.99,
    category: "batteries",
    stock: 0,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.9,
    reviews: 17,
    date: "2023-12-20",
  },
  {
    id: "solar-controller-mppt",
    name: "MPPT Solar Charge Controller",
    description: "Efficient charge controller with MPPT technology",
    price: 119.99,
    category: "controllers",
    stock: 30,
    featured: true,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.4,
    reviews: 61,
    date: "2024-01-10",
  },
  {
    id: "solar-led-light",
    name: "Solar LED Flood Light",
    description: "Bright and weatherproof outdoor lighting with solar power",
    price: 59.99,
    category: "lighting",
    stock: 75,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.1,
    reviews: 33,
    date: "2024-01-22",
  },
  {
    id: "solar-panel-kit-300w",
    name: "300W Solar Panel Kit",
    description: "Complete kit with panels, controller, and cables",
    price: 399.99,
    category: "solar-panels",
    stock: 12,
    featured: true,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.7,
    reviews: 46,
    date: "2024-02-05",
  },
  {
    id: "ac-dc-inverter",
    name: "500W AC to DC Inverter",
    description: "Inverter for hybrid solar systems",
    price: 159.99,
    category: "inverters",
    stock: 25,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.3,
    reviews: 20,
    date: "2024-02-17",
  },
  {
    id: "flexible-solar-panel",
    name: "Flexible 50W Solar Panel",
    description: "Bendable and lightweight solar panel for mobile use",
    price: 89.99,
    category: "solar-panels",
    stock: 22,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.6,
    reviews: 28,
    date: "2024-03-03",
  },
  {
    id: "solar-fan-kit",
    name: "Solar Fan Kit with Battery",
    description: "Kit includes solar fan and rechargeable battery",
    price: 79.99,
    category: "fans",
    stock: 40,
    featured: true,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.2,
    reviews: 18,
    date: "2024-03-18",
  },
  {
    id: "solar-string-lights",
    name: "Solar String Lights (Warm White)",
    description: "Decorative solar lights for garden and outdoor use",
    price: 29.99,
    category: "lighting",
    stock: 100,
    featured: false,
    image: "/placeholder.svg?height=300&width=300",
    rating: 4.5,
    reviews: 70,
    date: "2024-04-01",
  },
]

